# Generated by Django 5.2.5 on 2025-08-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainings/pictures/'),
        ),
        migrations.AddField(
            model_name='training',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='trainings/videos/'),
        ),
    ]
