# Generated by Django 5.2.5 on 2025-08-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0002_training_picture_training_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='traning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='professions.training'),
        ),
    ]
