# Generated by Django 5.2.5 on 2025-08-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0003_remove_training_comment_comment_traning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='traning',
        ),
        migrations.AddField(
            model_name='comment',
            name='traning_id',
            field=models.IntegerField(default=0),
        ),
    ]
