# Generated by Django 5.2.5 on 2025-08-22 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professions', '0004_remove_comment_traning_comment_traning_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='traning_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='professions.training'),
        ),
    ]
