# Generated by Django 5.2.5 on 2025-08-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buttom',
            new_name='Button',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='buttoms',
            new_name='buttons',
        ),
    ]
